config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'tasks#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :tasks 
  namespace :admin do
    resources :users
  end
  resources :labelings

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, 
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  before_destroy do
    throw :abort if User.where(admin: true).count < 2 && self.admin?
  end
  has_many :tasks, dependent: :destroy
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :if_not_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.includes(:tasks).all.order(created_at: :DESC)
  end


  def new
    @user = User.new
    @admin = current_user.admin if current_user
  end

  def create 
    @user = User.new(user_params)
    if @user.save 
      redirect_to admin_users_path, notice:"ユーザー#{@user.name}を登録しました。"
    else
      render 'new'
    end 
  end

  def edit
  end

  def show
    @user = User.find(params[:id])
  end
    
    
  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザー#{@user.name}を更新しました"
    else
      render 'edit'
    end
  end

  def destroy 
    if User.where(admin: true).count <= 1 && @user.admin?
      redirect_to admin_users_path, notice: "ユーザー#{@user.name}は削除することができません"
    else
      @user.destroy
      redirect_to admin_users_path, notice: "ユーザー#{@user.name}を削除しました"
    end
  end

  def confer_admin
    @user = User.find(params[:id])
    if @user.admin == false
      @user.admin = true
      @user.save
      flash[:notice] = '管理者権限を得ました'
      redirect_to admin_users_path
    elsif @user.admin == true && @user.id == current_user.id
      @user.admin = false
      @user.save
      flash[:notice] = '管理者権限を失効しました'
      redirect_to tasks_path
    else
      @user.admin = false
      @user.save
      flash[:notice] = '管理者権限がありません'
      redirect_to admin_users_path
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def if_not_admin
    if current_user == nil
      redirect_to new_session_path
    elsif current_user.admin?
      redirect_to tasks_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if logged_in?
      redirect_to tasks_path, notice: '既にログイン済です'
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to tasks_path(@user.id)
      else
        render 'new'
      end
  end

  def show
    @user = User.find(params[:id])
    @tasks = Task.where(user_id: @user.id)
  end

  private

  def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>ユーザ編集</h1>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with(model: [:admin, @user], local: true) do |f| %> 

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>


      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.check_box :admin ,{}, "true", "false" %>
      <%= f.label :admin, "管理者権限" %>

      <br>
      <%= f.submit "Create user", class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<h1>ユーザ一覧</h1>


<div class="md-5">
  <table class="table table-hover">
    <thead class="thead-default">
      <tr>
        <th>名前</th>
        <th>メールアドレス</th>
        <th>管理権限</th>
        <th>タスク数</th>
        <th>作成日</th>
        <th>更新日</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td class="light"><%= link_to user.name, [:admin, user] %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= link_to Task.where(user_id: user.id).length, tasks_path %></td>
        <td><%= user.created_at.strftime("%Y年%m月%d日") %></td>
        <td><%= user.updated_at.strftime("%Y年%m月%d日") %></td>
        <td><%= link_to '詳細', user_path(user.id), class: 'btn btn-primary' %></td>
        <td><%= link_to '編集', edit_admin_user_path(user), data: { confirm: '本当に編集していいですか？' }, class: 'btn btn-primary' %></td>
        <td><%= link_to '削除', [:admin, user], method: :delete, method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-danger' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'ユーザ新規登録', new_admin_user_path, class: 'btn btn-primary' %>
</div>

app/views/admin/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <% if @admin %>
    <%= link_to '一覧',admin_users_path, class: 'nav-link' %>
  <% end %>
    <%= form_with(model: [:admin, @user], local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.check_box :admin ,{}, "true", "false" %>
    <%= f.label :admin, "管理者権限" %>
    <br>
    <%= f.submit "Create user", class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<h1>ユーザー詳細</h1>
<div class="nav justify-content-end">
  <%= link_to '一覧', admin_users_path, class: 'nav-link'%>
  <table class="table table-hover">
    <tbody>
      <tr>
        <th>ユーザID</th>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <th>ユーザ名</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>作成日</th>
        <td><%= @user.created_at.strftime("%Y年%m月%d日") %></td>
      </tr>
      <tr>
        <th>更新日</th>
        <td><%= @user.updated_at.strftime("%Y年%m月%d日") %></td>
      </tr>
      <td><%= link_to '編集', edit_admin_user_path, data: { confirm: '本当に編集していいですか？' }, class: 'btn btn-primary' %></td>
      <td><%= link_to '削除', [:admin, @user], method: :delete, method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-danger' %></td>
    </tbody>
  </table>
</div>